### ISSUE TITLE
requirements is out of date

### ISSUE THREAD

**Issue by hydra3333** [jinxo13/FetchTV-Helpers#9] opened 2022-02-28 04:39 UTC
Hello and thanks for this tool.

The requirements.txt is out of date and caused a later version of jsonpickle to be uninstalled and an earlier version installed in its place.
Would it be possible to specify the dependency requirements without a version ?

I guess while I'm here, being new to this thing :  
I have  2x Fetch Mighty's.    
I know I have a recordings on each, however when I do   
`python3 ./fetchtv_upnp.py --recordings --ip=xx.xx.xx.21 --port=49152`   
It lists only 6 of all the recordings on one and none for the other.
Should I be using a different command to see what's on the Fetch boxes ?
Thanks.

**Comment by mesh-newbie** [comment] 2022-02-28 21:27
hi @hydra3333.
is your setup multiroom?
your using different IP's for each fetch when attempting a lookup?
are the FM's retail or through an ISP? and the same generation?
are all FB's setup on the same account?
you can currently see/play/menu recordings recorded on FM1 from FM2? does this also hold true if the internet is down?

my 2c :-)

**Comment by mesh-newbie** [comment] 2022-02-28 21:37
Supplement to the above @hydra3333 , can VLC see both FM's and play recordings from either?

**Comment by hydra3333** [comment] 2022-03-01 01:34
hi @mesh-newbie](https://github.com/mesh-newbie
> is your setup multiroom?
yes

> you're using different IP's for each fetch when attempting a lookup?
yes

> are the FM's retail or through an ISP? and the same generation?
retail, about 2 or 3 years apart, not sure how to tell what generation they are, M616T ?

> are all FB's setup on the same account?
yes

> you can currently see/play/menu recordings recorded on FM1 from FM2
yes

> ? does this also hold true if the internet is down?
don't know.  not sure if it should matter :)

> can VLC see both FM's and play recordings from either?
not sure how on a PC.
on a chromecast, it can see them as local network upnp devices but reports zero recordings on each

**Comment by mesh-newbie** [comment] 2022-03-01 01:52
Re VLC @hydra3333 simply [download](https://www.videolan.org/vlc/) and open.
Then look in
LOCAL NETWORK -> Universal Plug'n'Play
Your FM's "should" show up under title....   STB <your.ip-address>
As you click into each one... you should get a tree structure with Recordings and Movies.
The more you drill down, the more recordings/folder you will see... its a bit weird in that it only initially shows recordings as   files rather than a folder. Expand all doesn't work in this case.

But suffice to say... this is how I think the code is scraping the content/files/folders.

PS: I'm not the dev, just a casual user of the code.
PSS: You can actually download files too using VLC (sort of), but it's rather slow and cumbersome and its how I came across this script :p)

**Comment by hydra3333** [comment] 2022-03-01 03:08
OK.
Tried with VLC (ctrl-L then look at upnp) and the 2 servers show plus a folder tree on each containing Recordings and Movies.

I had a cleanup on the FMs last night, but plenty of recordings (from from free-to-air channels) definitely left on both FMs.

No files show up in any of the folders on either device on VLC nor ```python3 ./fetchtv_upnp.py --recordings --ip=xx.xx.xx.21 --port=49152```

**Comment by mesh-newbie** [comment] 2022-03-01 03:19
hi @hydra3333 , you noted that "**no files**" show up in VLC?!... oh my.. that's not a positive sign...
only @jinxo13 can answer.....but I suspect that in a multiroom config, fetch does something unique/special with upnp (encryption?? or even to an external API??) if not even VLC can drill down further than "Recordings" to either device :-(

Bugger!

![image](https://user-images.githubusercontent.com/8045203/156098699-3f36095a-2faf-41b0-abdc-2563a100cd98.png)

**Comment by hydra3333** [comment] 2022-03-01 04:27
I wish I saw what you had, in that attached pic !
Just a thought, does it show anything recorded from a subscribed channel ?

Oh well, a trade-off by the looks, I suppose I could disable multi-room and try again ... but multi-room is currently of more use to us :)

**Comment by jinxo13** [comment] 2022-05-25 12:46
@hydra3333 - regarding the requirements I've just set the minimum, so it shouldn't uninstall a more recent version anymore

**Comment by jinxo13** [comment] 2022-05-25 13:27
Unfortunately I only have 1 Fetch box, so I can't test/play the multi-room config :(
As @mesh-newbie mentioned if VLC isn't showing them then neither will the script.

@hydra3333 - It sounds like in multi-room may combine the content to appear as 1 library on your Fetch boxes?

**Comment by jinxo13** [comment] 2022-06-05 22:24
Closing this thread as the issue is resolved.

**Closed as completed by jinxo13** 2022-06-05 22:24 UTC
